/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudentClass = IDL.Variant({
  'Class1' : IDL.Null,
  'Class2' : IDL.Null,
  'Class3' : IDL.Null,
  'Class4' : IDL.Null,
  'Class5' : IDL.Null,
  'Nursery' : IDL.Null,
});
export const CreateStudentRequest = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'class' : StudentClass,
  'name' : IDL.Text,
  'motherName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'fatherName' : IDL.Text,
});
export const StudentId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Cash' : IDL.Null,
});
export const AdmissionFee = IDL.Record({
  'status' : PaymentStatus,
  'paymentMethod' : IDL.Opt(PaymentMethod),
});
export const MonthlyFee = IDL.Record({
  'apr' : PaymentStatus,
  'aug' : PaymentStatus,
  'dec' : PaymentStatus,
  'feb' : PaymentStatus,
  'jan' : PaymentStatus,
  'jul' : PaymentStatus,
  'jun' : PaymentStatus,
  'mar' : PaymentStatus,
  'may' : PaymentStatus,
  'nov' : PaymentStatus,
  'oct' : PaymentStatus,
  'sep' : PaymentStatus,
});
export const StudentPublic = IDL.Record({
  'id' : StudentId,
  'admissionFee' : AdmissionFee,
  'dateOfBirth' : IDL.Text,
  'class' : StudentClass,
  'name' : IDL.Text,
  'motherName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'fatherName' : IDL.Text,
  'monthlyFees' : MonthlyFee,
});
export const UpdateStudentRequest = IDL.Record({
  'id' : StudentId,
  'dateOfBirth' : IDL.Text,
  'class' : StudentClass,
  'name' : IDL.Text,
  'motherName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'fatherName' : IDL.Text,
});

export const idlService = IDL.Service({
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStudent' : IDL.Func([CreateStudentRequest], [StudentPublic], []),
  'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentPublic)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(StudentPublic)], ['query']),
  'login' : IDL.Func([], [UserRole], []),
  'setAdmissionFeeStatus' : IDL.Func(
      [StudentId, PaymentStatus, IDL.Opt(PaymentMethod)],
      [IDL.Bool],
      [],
    ),
  'setMonthlyFeeStatus' : IDL.Func(
      [StudentId, IDL.Text, PaymentStatus],
      [IDL.Bool],
      [],
    ),
  'updateStudent' : IDL.Func([UpdateStudentRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudentClass = IDL.Variant({
    'Class1' : IDL.Null,
    'Class2' : IDL.Null,
    'Class3' : IDL.Null,
    'Class4' : IDL.Null,
    'Class5' : IDL.Null,
    'Nursery' : IDL.Null,
  });
  const CreateStudentRequest = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'class' : StudentClass,
    'name' : IDL.Text,
    'motherName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'fatherName' : IDL.Text,
  });
  const StudentId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'UPI' : IDL.Null, 'Cash' : IDL.Null });
  const AdmissionFee = IDL.Record({
    'status' : PaymentStatus,
    'paymentMethod' : IDL.Opt(PaymentMethod),
  });
  const MonthlyFee = IDL.Record({
    'apr' : PaymentStatus,
    'aug' : PaymentStatus,
    'dec' : PaymentStatus,
    'feb' : PaymentStatus,
    'jan' : PaymentStatus,
    'jul' : PaymentStatus,
    'jun' : PaymentStatus,
    'mar' : PaymentStatus,
    'may' : PaymentStatus,
    'nov' : PaymentStatus,
    'oct' : PaymentStatus,
    'sep' : PaymentStatus,
  });
  const StudentPublic = IDL.Record({
    'id' : StudentId,
    'admissionFee' : AdmissionFee,
    'dateOfBirth' : IDL.Text,
    'class' : StudentClass,
    'name' : IDL.Text,
    'motherName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'fatherName' : IDL.Text,
    'monthlyFees' : MonthlyFee,
  });
  const UpdateStudentRequest = IDL.Record({
    'id' : StudentId,
    'dateOfBirth' : IDL.Text,
    'class' : StudentClass,
    'name' : IDL.Text,
    'motherName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'fatherName' : IDL.Text,
  });
  
  return IDL.Service({
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStudent' : IDL.Func([CreateStudentRequest], [StudentPublic], []),
    'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentPublic)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(StudentPublic)], ['query']),
    'login' : IDL.Func([], [UserRole], []),
    'setAdmissionFeeStatus' : IDL.Func(
        [StudentId, PaymentStatus, IDL.Opt(PaymentMethod)],
        [IDL.Bool],
        [],
      ),
    'setMonthlyFeeStatus' : IDL.Func(
        [StudentId, IDL.Text, PaymentStatus],
        [IDL.Bool],
        [],
      ),
    'updateStudent' : IDL.Func([UpdateStudentRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };