/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionFee {
  'status' : PaymentStatus,
  'paymentMethod' : [] | [PaymentMethod],
}
export interface CreateStudentRequest {
  'dateOfBirth' : string,
  'class' : StudentClass,
  'name' : string,
  'motherName' : string,
  'mobileNumber' : string,
  'fatherName' : string,
}
export interface MonthlyFee {
  'apr' : PaymentStatus,
  'aug' : PaymentStatus,
  'dec' : PaymentStatus,
  'feb' : PaymentStatus,
  'jan' : PaymentStatus,
  'jul' : PaymentStatus,
  'jun' : PaymentStatus,
  'mar' : PaymentStatus,
  'may' : PaymentStatus,
  'nov' : PaymentStatus,
  'oct' : PaymentStatus,
  'sep' : PaymentStatus,
}
export type PaymentMethod = { 'UPI' : null } |
  { 'Cash' : null };
export type PaymentStatus = { 'Paid' : null } |
  { 'Pending' : null };
export type StudentClass = { 'Class1' : null } |
  { 'Class2' : null } |
  { 'Class3' : null } |
  { 'Class4' : null } |
  { 'Class5' : null } |
  { 'Nursery' : null };
export type StudentId = bigint;
export interface StudentPublic {
  'id' : StudentId,
  'admissionFee' : AdmissionFee,
  'dateOfBirth' : string,
  'class' : StudentClass,
  'name' : string,
  'motherName' : string,
  'mobileNumber' : string,
  'fatherName' : string,
  'monthlyFees' : MonthlyFee,
}
export interface UpdateStudentRequest {
  'id' : StudentId,
  'dateOfBirth' : string,
  'class' : StudentClass,
  'name' : string,
  'motherName' : string,
  'mobileNumber' : string,
  'fatherName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStudent' : ActorMethod<[CreateStudentRequest], StudentPublic>,
  'deleteStudent' : ActorMethod<[StudentId], boolean>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getStudent' : ActorMethod<[StudentId], [] | [StudentPublic]>,
  'listStudents' : ActorMethod<[], Array<StudentPublic>>,
  'login' : ActorMethod<[], UserRole>,
  'setAdmissionFeeStatus' : ActorMethod<
    [StudentId, PaymentStatus, [] | [PaymentMethod]],
    boolean
  >,
  'setMonthlyFeeStatus' : ActorMethod<
    [StudentId, string, PaymentStatus],
    boolean
  >,
  'updateStudent' : ActorMethod<[UpdateStudentRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];