/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type AuthResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface StudentPublic {
    id: StudentId;
    admissionFee: AdmissionFee;
    dateOfBirth: string;
    class: StudentClass;
    name: string;
    motherName: string;
    mobileNumber: string;
    fatherName: string;
    monthlyFees: MonthlyFee;
}
export interface SessionInfo {
    username: string;
    role: UserRole;
}
export interface AdmissionFee {
    status: PaymentStatus;
    paymentMethod?: PaymentMethod;
}
export interface UpdateStudentRequest {
    id: StudentId;
    dateOfBirth: string;
    class: StudentClass;
    name: string;
    motherName: string;
    mobileNumber: string;
    fatherName: string;
}
export interface StaffInfo {
    username: string;
    role: UserRole;
}
export type StudentId = bigint;
export interface MonthlyFee {
    apr: PaymentStatus;
    aug: PaymentStatus;
    dec: PaymentStatus;
    feb: PaymentStatus;
    jan: PaymentStatus;
    jul: PaymentStatus;
    jun: PaymentStatus;
    mar: PaymentStatus;
    may: PaymentStatus;
    nov: PaymentStatus;
    oct: PaymentStatus;
    sep: PaymentStatus;
}
export interface CreateStudentRequest {
    dateOfBirth: string;
    class: StudentClass;
    name: string;
    motherName: string;
    mobileNumber: string;
    fatherName: string;
}
export enum PaymentMethod {
    UPI = "UPI",
    Cash = "Cash"
}
export enum PaymentStatus {
    Paid = "Paid",
    Pending = "Pending"
}
export enum StudentClass {
    Class1 = "Class1",
    Class2 = "Class2",
    Class3 = "Class3",
    Class4 = "Class4",
    Class5 = "Class5",
    Nursery = "Nursery"
}
export enum UserRole {
    admin = "admin",
    staff = "staff"
}
export interface backendInterface {
    createStaff(adminToken: string, username: string, password: string): Promise<AuthResult>;
    createStudent(token: string, req: CreateStudentRequest): Promise<StudentPublic>;
    deleteStaff(adminToken: string, username: string): Promise<boolean>;
    deleteStudent(token: string, id: StudentId): Promise<boolean>;
    getSession(token: string): Promise<SessionInfo | null>;
    getStudent(token: string, id: StudentId): Promise<StudentPublic | null>;
    listStaff(adminToken: string): Promise<Array<StaffInfo>>;
    listStudents(token: string): Promise<Array<StudentPublic>>;
    login(username: string, password: string): Promise<AuthResult>;
    logout(token: string): Promise<void>;
    setAdmissionFeeStatus(token: string, id: StudentId, status: PaymentStatus, paymentMethod: PaymentMethod | null): Promise<boolean>;
    setMonthlyFeeStatus(token: string, id: StudentId, month: string, status: PaymentStatus): Promise<boolean>;
    signup(username: string, password: string): Promise<AuthResult>;
    updateStudent(token: string, req: UpdateStudentRequest): Promise<boolean>;
}
import type { AdmissionFee as _AdmissionFee, AuthResult as _AuthResult, CreateStudentRequest as _CreateStudentRequest, MonthlyFee as _MonthlyFee, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, SessionInfo as _SessionInfo, StaffInfo as _StaffInfo, StudentClass as _StudentClass, StudentId as _StudentId, StudentPublic as _StudentPublic, UpdateStudentRequest as _UpdateStudentRequest, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createStaff(arg0: string, arg1: string, arg2: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(arg0, arg1, arg2);
                return from_candid_AuthResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(arg0, arg1, arg2);
            return from_candid_AuthResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: string, arg1: CreateStudentRequest): Promise<StudentPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0, to_candid_CreateStudentRequest_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_StudentPublic_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0, to_candid_CreateStudentRequest_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_StudentPublic_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteStaff(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0, arg1);
            return result;
        }
    }
    async deleteStudent(arg0: string, arg1: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0, arg1);
            return result;
        }
    }
    async getSession(arg0: string): Promise<SessionInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: string, arg1: StudentId): Promise<StudentPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStaff(arg0: string): Promise<Array<StaffInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStaff(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStaff(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(arg0: string): Promise<Array<StudentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_AuthResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_AuthResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async setAdmissionFeeStatus(arg0: string, arg1: StudentId, arg2: PaymentStatus, arg3: PaymentMethod | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmissionFeeStatus(arg0, arg1, to_candid_PaymentStatus_n29(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmissionFeeStatus(arg0, arg1, to_candid_PaymentStatus_n29(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async setMonthlyFeeStatus(arg0: string, arg1: StudentId, arg2: string, arg3: PaymentStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setMonthlyFeeStatus(arg0, arg1, arg2, to_candid_PaymentStatus_n29(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMonthlyFeeStatus(arg0, arg1, arg2, to_candid_PaymentStatus_n29(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async signup(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.signup(arg0, arg1);
                return from_candid_AuthResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signup(arg0, arg1);
            return from_candid_AuthResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudent(arg0: string, arg1: UpdateStudentRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, to_candid_UpdateStudentRequest_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, to_candid_UpdateStudentRequest_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdmissionFee_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdmissionFee): AdmissionFee {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_MonthlyFee_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MonthlyFee): MonthlyFee {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SessionInfo_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionInfo): SessionInfo {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StaffInfo_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffInfo): StaffInfo {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StudentClass_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentClass): StudentClass {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_StudentPublic_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentPublic): StudentPublic {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentMethod]): PaymentMethod | null {
    return value.length === 0 ? null : from_candid_PaymentMethod_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionInfo]): SessionInfo | null {
    return value.length === 0 ? null : from_candid_SessionInfo_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentPublic]): StudentPublic | null {
    return value.length === 0 ? null : from_candid_StudentPublic_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    paymentMethod: [] | [_PaymentMethod];
}): {
    status: PaymentStatus;
    paymentMethod?: PaymentMethod;
} {
    return {
        status: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.status),
        paymentMethod: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.paymentMethod))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    apr: _PaymentStatus;
    aug: _PaymentStatus;
    dec: _PaymentStatus;
    feb: _PaymentStatus;
    jan: _PaymentStatus;
    jul: _PaymentStatus;
    jun: _PaymentStatus;
    mar: _PaymentStatus;
    may: _PaymentStatus;
    nov: _PaymentStatus;
    oct: _PaymentStatus;
    sep: _PaymentStatus;
}): {
    apr: PaymentStatus;
    aug: PaymentStatus;
    dec: PaymentStatus;
    feb: PaymentStatus;
    jan: PaymentStatus;
    jul: PaymentStatus;
    jun: PaymentStatus;
    mar: PaymentStatus;
    may: PaymentStatus;
    nov: PaymentStatus;
    oct: PaymentStatus;
    sep: PaymentStatus;
} {
    return {
        apr: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.apr),
        aug: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.aug),
        dec: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.dec),
        feb: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.feb),
        jan: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.jan),
        jul: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.jul),
        jun: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.jun),
        mar: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.mar),
        may: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.may),
        nov: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.nov),
        oct: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.oct),
        sep: from_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.sep)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: _UserRole;
}): {
    username: string;
    role: UserRole;
} {
    return {
        username: value.username,
        role: from_candid_UserRole_n23(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    admissionFee: _AdmissionFee;
    dateOfBirth: string;
    class: _StudentClass;
    name: string;
    motherName: string;
    mobileNumber: string;
    fatherName: string;
    monthlyFees: _MonthlyFee;
}): {
    id: StudentId;
    admissionFee: AdmissionFee;
    dateOfBirth: string;
    class: StudentClass;
    name: string;
    motherName: string;
    mobileNumber: string;
    fatherName: string;
    monthlyFees: MonthlyFee;
} {
    return {
        id: value.id,
        admissionFee: from_candid_AdmissionFee_n9(_uploadFile, _downloadFile, value.admissionFee),
        dateOfBirth: value.dateOfBirth,
        class: from_candid_StudentClass_n16(_uploadFile, _downloadFile, value.class),
        name: value.name,
        motherName: value.motherName,
        mobileNumber: value.mobileNumber,
        fatherName: value.fatherName,
        monthlyFees: from_candid_MonthlyFee_n18(_uploadFile, _downloadFile, value.monthlyFees)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Pending: null;
}): PaymentStatus {
    return "Paid" in value ? PaymentStatus.Paid : "Pending" in value ? PaymentStatus.Pending : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    Cash: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "Cash" in value ? PaymentMethod.Cash : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Class1: null;
} | {
    Class2: null;
} | {
    Class3: null;
} | {
    Class4: null;
} | {
    Class5: null;
} | {
    Nursery: null;
}): StudentClass {
    return "Class1" in value ? StudentClass.Class1 : "Class2" in value ? StudentClass.Class2 : "Class3" in value ? StudentClass.Class3 : "Class4" in value ? StudentClass.Class4 : "Class5" in value ? StudentClass.Class5 : "Nursery" in value ? StudentClass.Nursery : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    staff: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "staff" in value ? UserRole.staff : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffInfo>): Array<StaffInfo> {
    return value.map((x)=>from_candid_StaffInfo_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentPublic>): Array<StudentPublic> {
    return value.map((x)=>from_candid_StudentPublic_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CreateStudentRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateStudentRequest): _CreateStudentRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_StudentClass_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentClass): _StudentClass {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStudentRequest_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStudentRequest): _UpdateStudentRequest {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod | null): [] | [_PaymentMethod] {
    return value === null ? candid_none() : candid_some(to_candid_PaymentMethod_n32(_uploadFile, _downloadFile, value));
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: StudentId;
    dateOfBirth: string;
    class: StudentClass;
    name: string;
    motherName: string;
    mobileNumber: string;
    fatherName: string;
}): {
    id: _StudentId;
    dateOfBirth: string;
    class: _StudentClass;
    name: string;
    motherName: string;
    mobileNumber: string;
    fatherName: string;
} {
    return {
        id: value.id,
        dateOfBirth: value.dateOfBirth,
        class: to_candid_StudentClass_n5(_uploadFile, _downloadFile, value.class),
        name: value.name,
        motherName: value.motherName,
        mobileNumber: value.mobileNumber,
        fatherName: value.fatherName
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    class: StudentClass;
    name: string;
    motherName: string;
    mobileNumber: string;
    fatherName: string;
}): {
    dateOfBirth: string;
    class: _StudentClass;
    name: string;
    motherName: string;
    mobileNumber: string;
    fatherName: string;
} {
    return {
        dateOfBirth: value.dateOfBirth,
        class: to_candid_StudentClass_n5(_uploadFile, _downloadFile, value.class),
        name: value.name,
        motherName: value.motherName,
        mobileNumber: value.mobileNumber,
        fatherName: value.fatherName
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    Paid: null;
} | {
    Pending: null;
} {
    return value == PaymentStatus.Paid ? {
        Paid: null
    } : value == PaymentStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    Cash: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.Cash ? {
        Cash: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentClass): {
    Class1: null;
} | {
    Class2: null;
} | {
    Class3: null;
} | {
    Class4: null;
} | {
    Class5: null;
} | {
    Nursery: null;
} {
    return value == StudentClass.Class1 ? {
        Class1: null
    } : value == StudentClass.Class2 ? {
        Class2: null
    } : value == StudentClass.Class3 ? {
        Class3: null
    } : value == StudentClass.Class4 ? {
        Class4: null
    } : value == StudentClass.Class5 ? {
        Class5: null
    } : value == StudentClass.Nursery ? {
        Nursery: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
